# Generated by Django 2.1.1 on 2018-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=False, to='blog.Post')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
